### PR TITLE
fix: map markers are back

### LINKED ISSUE #557: Map: validators missing on homepage, validators overview
Validator avatars do appear on the map on Validator Details pages, but missing from Overview and homepage

image

### PR DESCRIPTION
**Pull request by manuel-calavera**
Fixes #557

### CODE REVIEW

File: src/v2/stores/nodes.js [hunk 1]
```diff
@@ -48,7 +48,7 @@ class Store {
   });
 
   get mapMarkers() {
-    if (!this.network || !this.network.length) {
```
Comment (manuel-calavera) [inline src/v2/stores/nodes.js]: @sunnygleason network is Proxy object and does not have length property.

Comment (sunnygleason) [reply src/v2/stores/nodes.js]: @manuel-calavera interesting, this code was throwing before, hopefully the try/catch is enough

Here's the previous PR to fix the issue:

https://github.com/solana-labs/networkexplorer/pull/543/files
